//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToursApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Обращения
    {
        public int id_Обращения { get; set; }
        public string Текст { get; set; }
        public Nullable<System.DateTime> Дата_создания { get; set; }
        public int id_Сотрудника { get; set; }
        public int id_Статуса { get; set; }
        public int id_Образовательного_учреждения { get; set; }
        public int id_Жителя { get; set; }
    
        public virtual Жители Жители { get; set; }
        public virtual Образовательные_учреждения Образовательные_учреждения { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
        public virtual Статусы Статусы { get; set; }
    }
}
